### ISSUE TITLE
Design an issue template

### ISSUE THREAD

**Issue by jordansimsmith** [softeng-701-group-5/softeng-701-assignment-1#1]
As a software developer I would like to configure a standardisted issue template so that all of our issues are consistent.

**Acceptance Criteria**  
- Best practices for issue templates researched.
- Issue template defined for story (new feature) issues.
- Issue template defined for bug issues.

**Notes**  
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by salma-s** [comment]
Completed but can't make a PR yet - blocked by #3 Design a pull request template.

**Comment by Matteas-Eden** [comment]
@salma-s I closed #3 so go ahead and make that PR.
