### ISSUE TITLE
Add Modal Images when clicking a MediaCard image

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [softeng-701-group-5/softeng-701-assignment-1#101]
**User Story**
As a user, I'd like to have modal images, so that when an image is clicked, it expands to a bigger image, similar to that shown [here](https://www.w3schools.com/howto/howto_css_modal_images.asp)

**Acceptance Criteria**

- image changes on hover (so that user knows it's clickable)
- when clicked, it expands to have a bigger version pop-up
- there must be a close button to close the modal image

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

The user may find the image too small to read or want to view a bigger image

**Describe the solution you'd like**

For a modal image to appear when clicked

**Comment by Matteas-Eden** [comment]
Does there need to be a close button? Depending on the amount of space the modal image takes up on screen, I think it might be sufficient if the user clicks outside of the image to close it.

**Comment by HarrisonLeach1** [comment]
I changed the title to be more descriptive
