### ISSUE TITLE
Creation of Front-end and Backend labels

### ISSUE THREAD

**Issue by Kalashnikkov** [softeng-701-group-5/softeng-701-assignment-1#108]
**User Story**
As a Software Developer, I'd like to have labels that indicate whether an issue is Front-end related or Backend related, so that future developers can pick issues that are more related to their skill, and to help filter work on both ends.

**Acceptance Criteria**

- Label creation of `Front-End` and `Backend`

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

Wanting to participate, it is easier to pick off tasks that meet your skill level and preference. Having to go to the issue and reading the issue may not give all the information to see if a solution can be produced either in the front-end or backend.

Having someone to add this label to an associate issue is easier to read and manage.

**Describe the solution you'd like**

Label creation (Documentation is not needed as it is easy to understand.)

**Comment by Matteas-Eden** [comment]
Labels have been created, and are now visible under "Labels" on the Issues tab.
