### ISSUE TITLE
Home button goes to login page [Low]

### ISSUE THREAD

**Issue by FocalChord** [softeng-701-group-5/softeng-701-assignment-1#115]
**Bug Summary**

In essence, right now the home button goes to the login page but it shouldn't.

---

**Expected behavior**

The home button should go back to the feed page and there should be a log out button as well.

**Observed Behaviour**

Home button goes to login page

**Steps To Reproduce**

1. Click on home button, it goes to login page

**Environment**
- Version: 10.15.3
- OS: Mac OS X
- Browser: Chrome

**Comment by Dinith1** [comment]
LGTM
