### ISSUE TITLE
Implement Modals for each Card

### ISSUE THREAD

**Issue by MarioSinovcic** [softeng-701-group-5/softeng-701-assignment-1#116]
**User Story**
Also addresses #101 
As a user, I'd like to be able to see the rest of the information / text on each post so that I am not limited to the size of the card. 

**Acceptance Criteria**

- Modal for each card that shows the whole post
- Modals should be different for each sub group

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

The amount text from each post is limited to the card dimensions. 

**Describe the solution you'd like**

AC's followed, documentation and testing added where possible.

**Comment by Dinith1** [comment]
LGTM.

This issue is a prerequisite for future issues related to adding more detail to the cards/modals
