### ISSUE TITLE
Styling the app header to look more consistent 

### ISSUE THREAD

**Issue by baja156** [softeng-701-group-5/softeng-701-assignment-1#129]
**User Story**
As a user, I'd like to visit a website that has consistent, beautiful and crisp looking UI, so that I can seamlessly interact with the website creating a great UX.

**Acceptance Criteria**

- Styling the buttons to look more consistent
- Making sure the margins layout of the header and spacing around components is acceptable
- Wrapping the buttons (or maybe make the FEEDR and FAVORITE page buttons look smaller) in mobile view. You could alternatively, just have an icon button for favorites which would do the job too).
- Add the Feedr Logo to the app header, and use it as a button that redirects to feed page
- Make the header stay on the top even when you scroll.
- Highlight/do some UX thing to the page button when we're on that page
- Use the google Image/Name on the header

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
For a better UX

**Describe the solution you'd like**
See acceptance criteria, and **Please don't just use position = absolute, it doesn't work with resizing windows, use flex to get the desired layout**

[A guide to use flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

**Comment by FocalChord** [comment]
For reference, this is what it looks like right now

![Screen Shot 2020-04-10 at 11 32 49 AM](https://user-images.githubusercontent.com/31643423/78949505-d53d7a00-7b1f-11ea-99c3-e406fadc2041.png)

**Comment by lakshyaoberoi** [comment]
Following the team's latest update - deleted the favourites tab. Need to consider having an icon button instead?
![image](https://user-images.githubusercontent.com/48300301/79728484-1ca6e000-8342-11ea-8355-53cfbf7b11cf.png)
