### ISSUE TITLE
Define a code style

### ISSUE THREAD

**Issue by Minus20Five** [softeng-701-group-5/softeng-701-assignment-1#13]
As a software developer, I would like to follow a set of code style guidelines to improve readability.

**Acceptance Criteria** 

- Decision on Java code style
- Decision on Javascript code style
- eslintrc configured and added to client folder
- prettierrc configured and added to client folder
- style guidelines added to wiki
- add a link to the code styles in the CONTRIBUTING.md file, under the heading 'Coding Conventions'

**Comment by jordansimsmith** [comment]
@Minus20Five thoughts on extending the AC to include setting `eslintrc` and `prettierrc` for the JS project?

**Comment by Minus20Five** [comment]
Yup that sounds good to me.

**Comment by jordansimsmith** [comment]
@Minus20Five I'll take care of `eslintrc` and `prettierrc`, and will leave the backend stuff up to you.
