### ISSUE TITLE
Design a page (or equivalent) for dis/connecting apps

### ISSUE THREAD

**Issue by Dinith1** [softeng-701-group-5/softeng-701-assignment-1#137]
Related to #136 

**User Story**
As a user, I'd like to be able to connect and disconnect apps provided by Feedr, so that I can control what I see on my Feedr feed.

**Acceptance Criteria**

- Design/prototype
- Users should be able to connect apps that aren't connected, and disconnect apps that are connected
- E.g. A separate page with tiles showing which apps are connected, and clicking on a tile either pops up a confirmation modal to confirm connecting or disconnecting
- E.g. A drop down menu with switches, to 'switch on/off' different apps

**Notes**

---

**Comment by isabellelucy** [comment]
Prototype: https://www.figma.com/file/EPGy8YmVLnhCv3JVnmd5IG/Connecting-apps-prototype?node-id=0%3A1
