### ISSUE TITLE
Setup base react application

### ISSUE THREAD

**Issue by jordansimsmith** [softeng-701-group-5/softeng-701-assignment-1#15]
As a developer I would like to setup a base react application to provide a starting point for frontend feature development.

**Acceptance criteria**  
- Project bootstrapped
- Project structure setup
- Test page setup

**Comment by Matteas-Eden** [comment]
Since we're making a webapp, should we look into ways to host it as well? Would be great for the eventual demo.

**Comment by jordansimsmith** [comment]
> Since we're making a webapp, should we look into ways to host it as well? Would be great for the eventual demo.

Yeah, I think that could be a good idea. However, it would probably be out of the scope of this story. I can write another story for deployment later perhaps?

**Comment by Kalashnikkov** [comment]
> Since we're making a webapp, should we look into ways to host it as well? Would be great for the eventual demo.

Easiest that I have used is on Microsoft Azure - Its free, but hella slow.

I'm sure that some of us in the group have done this before, and _cooooouuuuld_ be in scope as it doesn't take that long to deploy (Deploys app off each push AFAIK)
