### ISSUE TITLE
Bug fix - weather/covid19 cards not showing correctly [High priority] 

### ISSUE THREAD

**Issue by isabellelucy** [softeng-701-group-5/softeng-701-assignment-1#178]
**Bug Summary**
Cards for COVID19 and weather are not showing up correctly 

**Test Case(s)**
Feedr main screen cards do not show up with usual functionality

---

**Expected behavior**
Cards should look like all the other cards in the Feedr main page.

**Observed Behaviour**
Cards appear but it looks like there is an extra card on top

---

**Screenshots**
![image](https://user-images.githubusercontent.com/42597241/80444257-5c368300-8965-11ea-8fad-b81c3ca923bf.png)

**Comment by FocalChord** [comment]
good spotting!
