### ISSUE TITLE
Define wireframe for frontend user feed

### ISSUE THREAD

**Issue by jordansimsmith** [softeng-701-group-5/softeng-701-assignment-1#19]
**User Story**
As a frontend developer, I'd like to design wireframes of the user feed, so that frontend development has a clear goal.

**Acceptance Criteria**

- Wireframes designed for the user feed (main screen)
- Feedback acquired from other developers/users
- Wireframes adapted as neccessary
- Wireframes added to wiki

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

N/A

**Describe the solution you'd like**

N/A

**Describe alternatives you've considered**

N/A

**Comment by Kalashnikkov** [comment]
This would need discussion with the front-end team yes? If so could we sort out a meeting time so that this issue can be resolved quickly

cc: @Matteas-Eden

**Comment by AlexanderTheGrape** [comment]
Is this meant to be simply designing the wireframe, or mocking up wireframe in React?

**Comment by Kalashnikkov** [comment]
@AlexanderTheGrape  I believe simply designing the wireframe so that we can actually start with development

**Comment by Matteas-Eden** [comment]
The wireframe was designed in a meeting and can be found [here](https://github.com/softeng-701-group-5/softeng-701-assignment-1/wiki/Frontend-Meeting).
