### ISSUE TITLE
Fetch reddit posts for a users homepage from the reddit api

### ISSUE THREAD

**Issue by HarrisonLeach1** [softeng-701-group-5/softeng-701-assignment-1#27]
**User Story**
As a backend developer, I'd like to fetch users home page/feed from the Reddit api, so that this data can then be mapped to a common data type and combined with their other feeds

**Acceptance Criteria**
- The posts retrieved must be specific to the user and the subreddits they are subscribed to.
- The user credentials should be stored in a config file, for now, which should NOT be committed.
- This config store must be generic such that it can be reused by other API clients 
- Changes must be unit-tested

**Notes**

**Comment by jordansimsmith** [comment]
@HarrisonLeach1 can the AC be extended to create a common config store of user credentials and other sensitive information? It will likely be reused by the other API teams. What do you think?

**Comment by HarrisonLeach1** [comment]
> @HarrisonLeach1 can the AC be extended to create a common config store of user credentials and other sensitive information? It will likely be reused by the other API teams. What do you thin

> @HarrisonLeach1 can the AC be extended to create a common config store of user credentials and other sensitive information? It will likely be reused by the other API teams. What do you think?

Yep, sounds good
