### ISSUE TITLE
Design a pull request template

### ISSUE THREAD

**Issue by jordansimsmith** [softeng-701-group-5/softeng-701-assignment-1#3]
As a software developer I would like to configure a standardisted pull request template so that all of our pull requests are consistent.

**Acceptance Criteria**  
- Best practices for pull request templates researched.
- Pull request template is defined.

**Notes**  
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by Matteas-Eden** [comment]
Relevant pull request was already closed before it was linked properly, so I'm closing this issue manually.
