### ISSUE TITLE
Define contributing guidelines

### ISSUE THREAD

**Issue by jordansimsmith** [softeng-701-group-5/softeng-701-assignment-1#4]
As a software developer I would like to define a set of contributing guidelines to help new contributors get started.

**Acceptance Criteria**  
- Best practices for contributing guidelines researched.
- Contributing guidelines defined.

**Notes**  
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by HarrisonLeach1** [comment]
Currently blocked by Design an issue template - #1 and Design a Pull Request template - #3.

These seem to be the most important components of contributing guidelines.
