### ISSUE TITLE
Implement a card on feed page

### ISSUE THREAD

**Issue by AlexanderTheGrape** [softeng-701-group-5/softeng-701-assignment-1#41]
**User Story**

As a user, I'd like to see a card entry in the feed, so that I have some media to look at. This card entry should have a title, an avatar, the name of the avatar (user who posted), main text, main image, a banner with the colour of media it is from (orange for reddit, for instance), and a hyperlink to the original post.

**Acceptance Criteria**

- Material UI components implemented
- Card contents & layout on the wiki adhered to
- Unit tests added & green

**Notes**
Loading multiple cards and their positioning on the page are out of scope for this issue. The code should allow the easy addition of these features later.

**Comment by Kalashnikkov** [comment]
LGTM, What does this mean in the acceptance criteria though?

>Unit tests added & green

**Comment by jordansimsmith** [comment]
> LGTM, What does this mean in the acceptance criteria though?
> 
> > Unit tests added & green

Green is slang for passing :heavy_check_mark:

**Comment by jordansimsmith** [comment]
https://github.com/softeng-701-group-5/softeng-701-assignment-1/wiki/Frontend-Meeting

Wireframe here.
