### ISSUE TITLE
Add commitzen to have descriptive commit messages

### ISSUE THREAD

**Issue by PreetPatel** [softeng-701-group-5/softeng-701-assignment-1#42]
**User Story**
As a developer, I'd like to be able to use a commit cli tool to create my commit messages, so that I can have consistently formatted commit messages.

**Acceptance Criteria**

- Add a module that handles creating commit messages
- Properly formatted commit messages (feat: | fix: | docs: | style:)...

**Notes**
have a look here for how it works: https://commitizen.github.io/cz-cli/

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
Currently, commit messages are very inconsistent across developer commits and having a tag in front of them and other formatting defined would be useful in creating much nicer commit messages for documentation

**Describe the solution you'd like**
Use something like commitizen to enforce a format

**Comment by jordansimsmith** [comment]
Would it be better to create a document in the wiki of how to write good commit messages, so that we can improve instead of relying on a tool?

**Comment by Matteas-Eden** [comment]
There's already a good outline of how to write commit messages given [here](https://chris.beams.io/posts/git-commit/), so I'm not convinced we even need to put much in the wiki. Maybe a footnote at best.

**Comment by PreetPatel** [comment]
I don't think putting it in a wiki is a good way to enforce it. No one would follow it.
Our commit history at this point is not consistent. We need a way to enforce it somewhere more than just shoving it in a wiki somewhere

**Comment by PreetPatel** [comment]
Another option could be having a defined template for writing the commit message in the PR template so its seen when creating the title of the PR

**Comment by jordansimsmith** [comment]
> Another option could be having a defined template for writing the commit message in the PR template so its seen when creating the title of the PR

I like this option, I think it’s more important that people learn about commit messages than that we have a clean history.

**Comment by PreetPatel** [comment]
> > Another option could be having a defined template for writing the commit message in the PR template so its seen when creating the title of the PR
> 
> I like this option, I think it’s more important that people learn about commit messages than that we have a clean history.

Have a look at how commitizen works.. it doesnt write messages for you.. it sets up a template.. just how we have PR Templates and don't expect to remember writing one up from scratch every time
