### ISSUE TITLE
Implement generic service provider flow

### ISSUE THREAD

**Issue by Minus20Five** [softeng-701-group-5/softeng-701-assignment-1#43]
**User Story**

As a developer, I would like to setup a generic service provider flow (template) which can be fleshed out by API teams.

**Acceptance Criteria**

- Define `ServiceProvider` interface 
- Define model classes which will be serialized to JSON and consumed by client
- ~Migrate `RedditFeedProvider` to service provider flow (+ wire up with controllers)~

**Notes**

This issue blocks API teams.

---

**Comment by HarrisonLeach1** [comment]
Cheers for this @Minus20Five, this will help out the other teams a lot

**Comment by HarrisonLeach1** [comment]
Blocks #28

**Comment by harmanlamba** [comment]
@Minus20Five, thanks for this! As discussed yesterday at the meeting, I'll go ahead and assign this issue to both of us.

**Comment by Minus20Five** [comment]
Bocked by #44
