### ISSUE TITLE
Add 'Getting Started' documentation to readme

### ISSUE THREAD

**Issue by HarrisonLeach1** [softeng-701-group-5/softeng-701-assignment-1#47]
**User Story**
As a new contributor to the repository, I'd like to have 'Getting Started' documentation, so that I can easily get my local development environment up and running, to build and test changes that I make.

**Acceptance Criteria**
- Steps to setup front-end in `client/README.md` 
- Steps to setup back-end in `server/README.md` 
- 'Getting Started' in main `README.md` links to the above documents
- Steps to setup development variables (copy instructions from [here](https://github.com/softeng-701-group-5/softeng-701-assignment-1/pull/29), under heading **For Local Testing**)
- Credentials should not be stored in the readme/wiki
- All instructions work for a contributor who has a newly cloned repository

**Notes**

**Comment by jordansimsmith** [comment]
@HarrisonLeach1 looks good, but should we have a user story as well as the AC?

**Comment by jordansimsmith** [comment]
Also, suggestion for the AC, that credentials are not stored in the readme/wiki

**Comment by HarrisonLeach1** [comment]
> @HarrisonLeach1 looks good, but should we have a user story as well as the AC?

Sorry about this, I forgot to uncomment it.
