### ISSUE TITLE
Adding Demo Credentials to Github Secrets

### ISSUE THREAD

**Issue by harmanlamba** [softeng-701-group-5/softeng-701-assignment-1#66]
**User Story**

As a developer, I'd like to add our provider test credentials to GitHub Secrets, so that I don't have to add them in our properties for each branch pull, or mistakenly push them.

**Acceptance Criteria**

-  Credentials are kept in Github Secrets

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

This feature is needed in order to securely store provider credentials, and not have to insert them manually, or mistakenly push them to Github. 

**Describe the solution you'd like**

The credentials ideally would get stored in Github Credentials

**Comment by PreetPatel** [comment]
How would we ensure this isn't mis-used since the repo is public?
