### ISSUE TITLE
API requests blocked by CORS [High Priority]

### ISSUE THREAD

**Issue by jordansimsmith** [softeng-701-group-5/softeng-701-assignment-1#67]
**Bug Summary**

When making API requests to our backend from the browser, requests are blocked due to the current CORS policy.

**Test Case(s)**

N/A

---

**Expected behavior**

API requests can be made from the browser without error.

**Observed Behaviour**

API requests made from the browser are blocked by the CORS policy.

**Steps To Reproduce**

1. Make a request from the browser. Easiest way is to fetch directly in the chrome console 
```javascript
fetch('http://localhost:8080');
```

**Environment**
- Version: n/a
- OS: Manjaro Linux
- Browser: Chromium

---

**Code Examples**

**Stack Trace**

**Screenshots**

**Error Report**

---

**Additional context**

**Comment by harmanlamba** [comment]
Looks good to me! Nice catch @jordansimsmith ! I think we should fix this ASAP, due to its high severity.

**Comment by TCHE614** [comment]
Good find @jordansimsmith the behaviour is not ideal.
