### ISSUE TITLE
Extract twitter images from tweet body and render on Media Card

### ISSUE THREAD

**Issue by jordansimsmith** [softeng-701-group-5/softeng-701-assignment-1#82]
**User Story**

As a frontend developer, I'd like to extract the twitter images from the tweet body and render that using the MediaCard image property so that twitter images are visible.

**Acceptance Criteria**

- Tweet images are extracted (and removed) from the tweet body (currently just links)
- Tweet image (single/first) is rendered as an image in the media card.

**Notes**
`src/common/mapping.js` contains the code responsible for mapping the api response data to the card properties. May have to use some regex to extract these links.
Some of these links are not images but links to other sites. You will have to distinguish these.

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

It is more useful to see the tweet image rendered instead of just the URL, as sometimes the tweet makes more sense with the image.

**Describe the solution you'd like**

Have the media card render the tweet image instead of just outputting the link.

**Comment by PreetPatel** [comment]
On it
