### ISSUE TITLE
Provide links to posts on Reddit and HackerNews media cards

### ISSUE THREAD

**Issue by HarrisonLeach1** [softeng-701-group-5/softeng-701-assignment-1#90]
**User Story**
As a user, I'd like to have a link to Reddit and HackerNews posts, so that I can find more information about them if they interest me.

**Acceptance Criteria**
- Links are obvious to the user, but not invasive
- Links go to the correct post on the original website
- If a URL does not exist it is clear that there is no link

**Notes**
This could be possible for Twitter, however it is currently not on the data model.

**Comment by HarrisonLeach1** [comment]
Titles could be highlighted blue for links

**Comment by Dinith1** [comment]
@FocalChord should this still be open? I'm assuming it should be, as the linked PR was closed (not completed). Just asking just in case
