### ISSUE TITLE
Implement support for customising layout of feed page

### ISSUE THREAD

**Issue by Matteas-Eden** [softeng-701-group-5/softeng-701-assignment-1#91]
**User Story**

As a user, I'd like to be able to modify the layout of the feed page, so that I can separate and organise my different media feeds into distinct columns.

**Acceptance Criteria**

- Able to dynamically to create columns that house cards exclusively from a specific media feed
- The media feed being shown in a column is selectable via a combo-box

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
I'm always frustrated when I load up Feedr and I'm inundated with tweets when I want to see notifications from other sites, such as Reddit.

**Describe the solution you'd like**
I'd like to be able to split the feeds into different parts of the page, as opposed to having all of media aggregated into a single area.

**Comment by bradleycoleman** [comment]
I like this idea. One question: is a 'media feed' a feed from just one source, or would it be able to aggregate from a few user-defined sources like the feed described by #92. I would prefer the latter.
